### ISSUE TITLE
Whitelisting doesn't work?

### ISSUE THREAD

**Issue by TwizzyDizzy** [RocketChat/Rocket.Chat.GitHub.Bot#13]
Hey @theorenck 

In [this comment](https://github.com/RocketChat/Rocket.Chat/issues/9838#issuecomment-367836009) @JSzaszvari could add a label without being whitelisted in [the bot configuration](https://github.com/RocketChat/Rocket.Chat.GitHub.Bot/blob/master/.github/bot-config.yml).

This is not as it is intended, is it?

Cheers
Thomas

**Comment by JSzaszvari** [comment]
@TwizzyDizzy It is white-listed https://github.com/RocketChat/Rocket.Chat/blob/develop/.github/bot-config.yml

**Comment by TwizzyDizzy** [comment]
Ah! So it seems the Bot configuration has been moved to the main server repo instead of this one or is now a per-repo configuration. I see.

Cheers
Thomas
